version: "2"
services:
  openldap:
    image: osixia/openldap
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"

  openldap-admin:
    image: osixia/phpldapadmin
    container_name: openldap-admin
    hostname: openldap-admin
    ports:
      - "6443:443"
    links:
      - "openldap:openldap"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
